name: tvmaze_app
description: A TV shows app.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  dartz: ^0.10.1
  flutter_html: ^2.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  local_auth: ^2.1.3
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true