// Mocks generated by Mockito 5.3.2 from annotations
// in tvmaze_app/test/modules/shows/show_detail/show_detail_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tvmaze_app/core/failures/failures.dart' as _i5;
import 'package:tvmaze_app/modules/shows/shared/model/episode.dart' as _i7;
import 'package:tvmaze_app/modules/shows/shared/model/show.dart' as _i6;
import 'package:tvmaze_app/modules/shows/shared/repository/show_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowRepository extends _i1.Mock implements _i3.ShowRepository {
  MockShowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i6.Show>>> getShows(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getShows,
          [page],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i6.Show>>>.value(
                _FakeEither_0<_i5.Failure, _i2.IList<_i6.Show>>(
          this,
          Invocation.method(
            #getShows,
            [page],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i6.Show>>>);
  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i2.IList<_i7.Episode>>> getEpisodesFromShow(
          int? showId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesFromShow,
          [showId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i7.Episode>>>.value(
                _FakeEither_0<_i5.Failure, _i2.IList<_i7.Episode>>(
          this,
          Invocation.method(
            #getEpisodesFromShow,
            [showId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i7.Episode>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i6.Show>>> toggleFavoriteShow(
    int? showId,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavoriteShow,
          [
            showId,
            isFavorite,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i6.Show>>>.value(
                _FakeEither_0<_i5.Failure, _i2.IList<_i6.Show>>(
          this,
          Invocation.method(
            #toggleFavoriteShow,
            [
              showId,
              isFavorite,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.IList<_i6.Show>>>);
}
